site_name: Kitchen Notes
theme:
  name: material
  features:
    - content.tabs.link
plugins:
  - search
  - tags:
      tags_file: index.md
markdown_extensions:
  - admonition
  - meta
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
nav:
  - 'Index': index.md
  - Sourdough:
    - 'Starter and Discard': 'sourdough/starter-and-discard.md'
    - 'Whole Wheat Flax Sandwich Loaf': 'sourdough/ww-flax-sammy.md'
    - 'Donuts': 'sourdough/donuts.md'