site_name: In The Kitchen
theme:
  name: material
  features:
    - navigation.tabs
plugins:
  - search
  - tags:
      tags_file: index.md
markdown_extensions:
  - admonition
  - meta
  - pymdownx.snippets
nav:
  - Home: index.md
  - Recipies:
    - Sourdough:
      - 'Whole Wheat Flax Sandwich Loaf': 'sourdough/ww-flax-sammy.md'