site_name: Kitchen Instructions
theme:
  name: material
plugins:
  - search
  - tags:
      tags_file: index.md
markdown_extensions:
  - admonition
  - meta
  - pymdownx.snippets
nav:
  - 'Index': index.md
  - Sourdough:
    - 'Starter and Discard': 'sourdough/starter-and-discard.md'
    - 'Whole Wheat Flax Sandwich Loaf': 'sourdough/ww-flax-sammy.md'
    - 'Donuts': 'sourdough/donuts.md'